"""Write the findings back into the codebase as declarations, plus a gate.

Inference is the right tool for a repo you do not control and cannot mandate
anything about — which is exactly where you are the first time you point this at a
codebase. For code you *own*, declaring and enforcing beats inferring: it is
complete, it works in every language, and it fails on the exact line instead of
reporting "no path found".

So `adopt` graduates a repo off inference. After it runs, the register is
generated from the code's own declarations and the next run is declared rather
than guessed. That converts "tell us before you add an AI service" from something
an annual sweep discovers into a compile error.

Two decisions worth knowing about.

**It generates the wrapper, not just the declaration.** The load-bearing part is
not the list of processes; it is that every call site must pass a `feature`
argument whose type is `keyof typeof AI_PROCESSES`. Without the wrapper the clever
bit does not come with it, and the declaration is just a comment that happens to
compile.

**`held_by` is generated EMPTY.** Not "TODO", not "under review" — empty. An empty
control renders as **nothing** in the register, which is the honest state of a
process nobody has yet written a control for. Pre-filling it with placeholder
reassurance would launder an unknown into a claim, in the one column that matters.

**Nothing is published.** `adopt` vendors a single file into the repo. No package
to install, no registry to authenticate against, no version to keep in step —
because a public tool cannot assume a company has, or wants, an internal package
registry, and a shared dependency is the part of this that would rot.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .catalog import Catalog
from .scan import ScanReport, scan
from .schema import ACTIONS

TS_TEMPLATE = '''\
// Generated by heldby (https://github.com/receipting/heldby). Vendored on purpose:
// no package to install and no version to keep in step.
//
// This file is the source of truth for this repo's AI register. Two rules:
//
//   1. Every model call passes a `feature` whose type is `AIFeature`, so a new AI
//      call cannot ship without adding an entry below — it will not compile.
//   2. `heldBy` is the only column that matters. Name the specific thing standing
//      between the model's output and a real-world effect. Not "we have guardrails".
//      The entry has to survive an auditor reading the code next to it. If the
//      honest answer is nothing, leave it empty — the register will say so.

export type AIClass = 'read' | 'decide' | 'converse' | 'write'

/**
 * Read     — turns a document or message into structured data, checked against
 *            something real. If it cannot be checked against the world, not Read.
 * Decide   — proposes an action with a consequential effect. No person on the fast
 *            path by design; bounded by deterministic gates plus a threshold.
 * Converse — answers the person who asked, them and us and nobody else, and does
 *            nothing. All three closed-loop tests must hold.
 * Write    — produces prose the system carries to someone else. A named person
 *            edits and releases it, and the record says who.
 *
 * Where a process spans two, the STRICTER governs: Read < Converse < Decide < Write.
 */
export type ProtectedAction =
{actions}

export interface AIProcess {{
  /** The stricter class, where a process spans two. */
  class: AIClass
  /** The model this call site pins. */
  model: string
  /** One line, written for the register a customer reads. */
  does: string
  /** What this can reach when it is wrong. */
  reaches: readonly ProtectedAction[]
  /** The specific control between the output and the effect. Empty means nothing does. */
  heldBy: string
}}

/**
 * Identity function, and the `const` type parameter is doing the work: it
 * validates every entry against AIProcess AND preserves the keys as literals, so
 * `AIFeature` below is a union of the actual process names rather than `string`.
 */
export function defineProcesses<const T extends Record<string, AIProcess>>(processes: T): T {{
  return processes
}}

export const AI_PROCESSES = defineProcesses({{
{processes}}})

/** The union of declared process names. A call site cannot pass anything else. */
export type AIFeature = keyof typeof AI_PROCESSES

/**
 * Pass this into your model client's metadata. It exists so that `feature` is
 * REQUIRED and TYPED at every call site — which is the whole mechanism. Construct
 * your provider client in this file too, and `heldby lint` will hold that line.
 */
export function modelMeta(feature: AIFeature): {{ process: string; model: string }} {{
  return {{ process: String(feature), model: AI_PROCESSES[feature].model }}
}}
'''

PY_TEMPLATE = '''\
"""Generated by heldby (https://github.com/receipting/heldby). Vendored on purpose:
no package to install and no version to keep in step.

This file is the source of truth for this repo's AI register. Two rules:

1. Every model call passes a ``feature`` from ``AIFeature``, so a new AI call
   cannot ship without adding an entry below.
2. ``held_by`` is the only column that matters. Name the specific thing standing
   between the model's output and a real-world effect. Not "we have guardrails".
   The entry has to survive an auditor reading the code next to it. If the honest
   answer is nothing, leave it empty — the register will say so.

Read     — turns a document or message into structured data, checked against
           something real. If it cannot be checked against the world, not Read.
Decide   — proposes an action with a consequential effect. No person on the fast
           path by design; bounded by deterministic gates plus a threshold.
Converse — answers the person who asked, them and us and nobody else, and does
           nothing. All three closed-loop tests must hold.
Write    — produces prose the system carries to someone else. A named person
           edits and releases it, and the record says who.

Where a process spans two, the STRICTER governs: Read < Converse < Decide < Write.

AI_PROCESSES must stay a plain dict LITERAL. Tooling reads it with
``ast.literal_eval`` rather than importing this module, so that collecting the
register never needs your runtime dependencies or a database connection.
"""

from typing import Literal

AIClass = Literal["read", "decide", "converse", "write"]

ProtectedAction = Literal[
{actions}
]

AI_PROCESSES: dict[str, dict] = {{
{processes}}}

AIFeature = Literal[
{feature_names}
]


def model_for(feature: str) -> str:
    """The declared model for a process. Read it from here rather than hardcoding
    it at the call site, so the declared model cannot drift from the sent one."""
    return AI_PROCESSES[feature]["model"]
'''


@dataclass
class AdoptPlan:
    declaration_path: Path
    config_path: Path
    baseline_path: Path
    ecosystem: str
    processes: list[str]
    gateway_modules: list[str]
    other_model_files: list[str]
    existing: list[Path]

    @property
    def blocked(self) -> bool:
        return bool(self.existing)


def _guess_ecosystem(report: ScanReport) -> str:
    """Whichever language the repo actually has more of."""
    return "py" if report.languages.get("py", 0) > report.languages.get("ts", 0) else "ts"


#: Path fragments suggesting a file's job is talking to a model provider.
GATEWAY_HINTS = (
    "gateway", "ai-", "ai_", "/ai", "llm", "anthropic", "openai", "bedrock",
    "model", "provider", "completion", "inference",
)


def _choose_gateway_module(report: ScanReport) -> tuple[list[str], list[str]]:
    """Pick ONE designated gateway module, and name the rest as existing bypasses.

    Returns (gateway_modules, other_files_with_model_calls).

    The tempting shortcut is to declare every file that currently calls a model to
    be a gateway module, which makes the gate green instantly. It also makes it
    meaningless — it green-lights the bypasses by renaming them, and the tool then
    reports "every model call is made in the gateway" about a repo with calls
    scattered across a dozen files. That is exactly the kind of clean report this
    whole tool exists to distrust.

    So: one module is designated, everything else is baselined as known debt. The
    gate still passes on day one, but through an explicit shrink-only list that
    says out loud what has not been fixed yet.
    """
    counts: dict[str, int] = {}
    for site in report.sites:
        if site.kind == "model" and site.why in {"symbol", "member", "url", "url-literal"}:
            counts[site.file] = counts.get(site.file, 0) + 1
    if not counts:
        return [], []

    def rank(path: str) -> tuple[int, int]:
        hinted = 1 if any(hint in path.lower() for hint in GATEWAY_HINTS) else 0
        return (hinted, counts[path])

    best = max(sorted(counts), key=rank)
    return [best], sorted(f for f in counts if f != best)


def plan(root: Path, catalog: Catalog) -> AdoptPlan:
    report = scan(root, catalog, ignore_declarations=True)
    ecosystem = _guess_ecosystem(report)

    names = sorted({n for names in report.labels.values() for n in names})
    gateways, others = _choose_gateway_module(report)
    declaration = root / ("ai_register.py" if ecosystem == "py" else "ai-register.ts")
    config = root / "heldby.yml"
    baseline = root / ".heldby-baseline.json"

    return AdoptPlan(
        declaration_path=declaration,
        config_path=config,
        baseline_path=baseline,
        ecosystem=ecosystem,
        processes=names,
        gateway_modules=gateways,
        other_model_files=others,
        existing=[p for p in (declaration, config) if p.exists()],
    )


def _ts_entry(name: str) -> str:
    return (
        f"  {name!r}: {{\n"
        f"    class: 'read',        // CHECK THIS. Read < Converse < Decide < Write.\n"
        f"    model: '',            // the model this call site pins\n"
        f"    does: '',             // one line, for the register a customer reads\n"
        f"    reaches: [],          // what it can reach when it is wrong\n"
        f"    heldBy: '',           // empty means NOTHING holds it, and says so\n"
        f"  }},\n"
    )


def _py_entry(name: str) -> str:
    return (
        f'    "{name}": {{\n'
        f'        "class": "read",   # CHECK THIS. Read < Converse < Decide < Write.\n'
        f'        "model": "",       # the model this call site pins\n'
        f'        "does": "",        # one line, for the register a customer reads\n'
        f'        "reaches": [],     # what it can reach when it is wrong\n'
        f'        "held_by": "",     # empty means NOTHING holds it, and says so\n'
        f"    }},\n"
    )


def render_declaration(plan_: AdoptPlan) -> str:
    names = plan_.processes or ["unnamed-process"]
    if plan_.ecosystem == "py":
        return PY_TEMPLATE.format(
            actions="\n".join(f'    "{a}",' for a in sorted(ACTIONS)),
            processes="".join(_py_entry(n) for n in names),
            feature_names="\n".join(f'    "{n}",' for n in names),
        )
    return TS_TEMPLATE.format(
        actions="\n".join(f"  | {a!r}" for a in sorted(ACTIONS)),
        processes="".join(_ts_entry(n) for n in names),
    )


def render_config(plan_: AdoptPlan) -> str:
    modules = plan_.gateway_modules or ["src/"]
    listed = "\n".join(f"  - {m}" for m in modules)
    return f"""\
# heldby configuration. See https://github.com/receipting/heldby
#
# gateway_modules: the ONLY places a model client may be constructed or a provider
# host named. heldby lint fails on a model call anywhere else.
#
# ONE module was designated, chosen as the likeliest candidate from where model
# calls are made today. Every other file that calls a model is recorded in the
# baseline below as known debt, NOT promoted to a gateway — declaring them all to
# be gateways would make this gate pass by renaming the problem.
#
# Change this if the tool picked wrong. It guessed.
gateway_modules:
{listed}

# Excluded paths are NOT covered by the gate's claim, and heldby says so in its
# output every time it passes. A scope you cannot see is a scope you cannot audit.
exclude: []

# Pre-existing bypasses, accepted deliberately. This file may only SHRINK.
baseline: .heldby-baseline.json

declaration: {plan_.declaration_path.name}
"""
